#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
# Copy and restore dependencies for the Application project
COPY ./BibliotecaApi/Biblioteca.Application/*.csproj ./BibliotecaApi/Biblioteca.Application/
RUN dotnet restore ./BibliotecaApi/Biblioteca.Application/Biblioteca.Application.csproj

# Copy and restore dependencies for the Domain project
COPY ./BibliotecaApi/Biblioteca.Domain/*.csproj ./BibliotecaApi/Biblioteca.Domain/
RUN dotnet restore ./BibliotecaApi/Biblioteca.Domain/Biblioteca.Domain.csproj

# Copy and restore dependencies for the Domain project
COPY ./BibliotecaApi/Biblioteca.Domain.Core/*.csproj ./BibliotecaApi/Biblioteca.Domain.Core/
RUN dotnet restore ./BibliotecaApi/Biblioteca.Domain.Core/Biblioteca.Domain.csproj

# Copy and restore dependencies for the Domain project
COPY ./BibliotecaApi/Biblioteca.Infra.CrossCutting.Identity/*.csproj ./BibliotecaApi/Biblioteca.Infra.CrossCutting.Identity/
RUN dotnet restore ./BibliotecaApi/Biblioteca.Infra.CrossCutting.Identity/Biblioteca.Domain.csproj

# Copy and restore dependencies for the Domain project
COPY ./BibliotecaApi/Biblioteca.Infra.CrossCutting.IoC/*.csproj ./BibliotecaApi/Biblioteca.Infra.CrossCutting.IoC/
RUN dotnet restore ./BibliotecaApi/Biblioteca.Infra.CrossCutting.IoC/Biblioteca.Domain.csproj

# Copy and restore dependencies for the Domain project
COPY ./BibliotecaApi/Biblioteca.Infra.Data/*.csproj ./BibliotecaApi/Biblioteca.Infra.Data/
RUN dotnet restore ./BibliotecaApi/Biblioteca.Infra.Data/Biblioteca.Domain.csproj

# Copy and restore dependencies for the Domain project
#COPY ./BibliotecaApi/Biblioteca.TesteUnitario/*.csproj ./BibliotecaApi/Biblioteca.TesteUnitario/
#RUN dotnet restore ./BibliotecaApi/Biblioteca.Domain/Biblioteca.Domain.csproj

RUN dotnet restore "Biblioteca/Biblioteca.Api.csproj"
COPY . .
WORKDIR "/src/Biblioteca"
RUN dotnet build "Biblioteca.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Biblioteca.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Biblioteca.Api.dll"]